UI helper blueprint library
TheEmidee/UE4CoreExtensions pull request #29
Opened 2024-07-23 09:36 UTC by ThibNach

added function to get widget associated to a list view item
added function to get focused widget from an array of widgets

2024-07-23 10:01 UTC, VectorGamez requested changes

2024-07-23 10:01 UTC, VectorGamez commented on Source/CoreExtensions/Private/BlueprintLibraries/UCoreExtUIBlueprintLibrary.cpp
> +#include "Kismet/GameplayStatics.h"
<>

2024-07-23 10:01 UTC, VectorGamez commented on Source/CoreExtensions/Public/BlueprintLibraries/UCoreExtUIBlueprintLibrary.h
> +#include "CoreMinimal.h"
<>

2024-07-23 10:01 UTC, VectorGamez commented on Source/CoreExtensions/Public/BlueprintLibraries/UCoreExtUIBlueprintLibrary.h
> +#include "Kismet/BlueprintFunctionLibrary.h"
<>

2024-07-23 13:25 UTC, ThibNach commented on Source/CoreExtensions/Private/BlueprintLibraries/UCoreExtUIBlueprintLibrary.cpp
> +#include "Kismet/GameplayStatics.h"
Done

2024-07-23 13:25 UTC, ThibNach commented on Source/CoreExtensions/Public/BlueprintLibraries/UCoreExtUIBlueprintLibrary.h
> +#include "CoreMinimal.h"
Done

2024-07-23 13:25 UTC, ThibNach commented on Source/CoreExtensions/Public/BlueprintLibraries/UCoreExtUIBlueprintLibrary.h
> +#include "Kismet/BlueprintFunctionLibrary.h"
Done

2024-07-23 13:55 UTC, VectorGamez approved these changes

2024-07-23 14:04 UTC, MaxDaniels approved these changes

2024-07-26 07:28 UTC, Fr0oZzFred approved these changes

2024-07-30 14:32 UTC, merged