feature/core_ext_object_class
TheEmidee/UE4CoreExtensions pull request #6
Opened 2022-03-04 08:58 UTC by VectorGamez

2022-03-04 12:17 UTC, TheEmidee requested changes
Would name that object `ObjectWithWorld`
Would put it in a `Core` folder instead

2022-03-04 13:20 UTC, VectorGamez commented
> 

Done

2022-03-07 08:45 UTC, TheEmidee approved these changes

2022-03-07 10:21 UTC, TheEmidee approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/theemidee/uecoreextensions/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @VectorGamez)



<!-- Sent from Reviewable.io -->

2022-03-07 10:22 UTC, merged